theme: just-the-docs

url: https://mgroeber9110.github.io/just-the-docs-test

aux_links:
  Repository: https://github.com/mgroeber9110/just-the-docs-test

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/mgroeber9110/just-the-docs-test"
gh_edit_branch: "main"
gh_edit_source: "TechDocs/Markdown"
gh_edit_view_mode: "tree"

# Jekyll plugins to simplify working with plain Markdown files
# (copied from default jekyll-build-pages action)
plugins:
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-default-layout

github: [metadata]

defaults:
  -
    scope:
      path: "" # all files
    values:
      # Turn off liquid rendering due to problems with {{...}} in code
      render_with_liquid: false
  -
    scope:
      path: "assets"
    values:
      # Turn liquid rendering back on for theme assets
      render_with_liquid: true