theme: just-the-docs

aux_links:
  Repository: https://github.com/mgroeber9110/just-the-docs-test

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/mgroeber9110/just-the-docs-test"
gh_edit_branch: "main"
gh_edit_source: "TechDocs/Markdown"
gh_edit_view_mode: "tree"

# Jekyll plugins to simplify working with plain Markdown files
# (copied from default gh-pages action)
plugins:
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-default-layout
