title: \#FreeGEOS
description: Technical documentation for \#FreeGEOS
theme: just-the-docs

url: https://mgroeber9110.github.io/pcgeos

aux_links:
  Repository: https://github.com/mgroeber9110/pcgeos

gh_edit_source: TechDocs/Markdown